name: Aprendiendo GitHub Actions
run-name: Estoy aprendiendo GitHub Actions

on: 
  push:
    branches:
      - '**'

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name:   Definir variables
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Correr script
        run: python main.py
