name: TriggersCG
run-name: Estoy aprendiendo a usar diferentes triggers

on:
  push:
    branches:
      - master
    pull_request:
      types: [opened, synchronize, reopened]
      paths:
        - '**py'
      issues:
        types:
         - labeled
      workflow_dispatch:
        inputs:
          lenguaje_favorito:
            description: 'lenguaje favorito'
            default: Python
            required: true
            type: choice
            options:
            - Python
            - JavaScript
            - Go
          nombre:
            description: 'MY NAME'
            required: true
            default: Cristian
            type: string
  schedule:
    - cron: '18 02 * * *' 
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir nombe
        run: echo "USERNAME=${{inputs.nombre}}" >> $GITHUB_ENV
      - name: Correr script
        run: python main.py
  hola-mundo:
    if: ${{github.event_name != 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV
      - name: Correr script
        run: python main.py


          
